version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"
  jobs:
    # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
    install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --no-default-groups --group docs

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub
