version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"  # py_ver
  jobs:
    # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv sync --all-extras --only-group docs
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub
