contact_links:
{%- if cookiecutter.use_discord_community == "yes" %}
  - name: Discord
    url: https://discord.gg/{{ cookiecutter.discord_invite }}
    about: Please ask and answer questions here.
{%- endif %}
