name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

jobs:
  Nox:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: snok/install-poetry@v1
    - uses: daisylb/setup-nox@v2.1.0
    - run: nox
