name: Codecov

on:
  pull_request:
  push:
    branches:
      - {{ cookiecutter.main_branch }}
      - rc

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install project
        run: uv sync --all-extras --no-default-groups --group tests

      - name: Generate coverage report
        run: |
          uv run pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage.xml
          flags: unittests
